# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"

  assume_role {
    role_arn = "arn:aws:iam::459532803582:role/OrganizationAccountAccessRole"
  }

  default_tags {
    tags = {
      Project     = "Landing-Zone"
      ManagedBy   = "Terraform"
      Environment = "Log-Archive"
    }
  }
}
