# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"

  assume_role {
    role_arn = "arn:aws:iam::677466569873:role/OrganizationAccountAccessRole"
  }

  default_tags {
    tags = {
      Project     = "landing-zone"
      ManagedBy   = "Terraform"
      Environment = "shared-services"
    }
  }
}
