# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tfstate-management-582071018932-us-east-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "accounts/workload/vpc/terraform.tfstate"
    region         = "us-east-1"
  }
}
